# Generated by Django 2.0.1 on 2020-02-23 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_country'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificate',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Country'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='me_as_teacher',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skypeId',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.SubCategory'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'professional'), (2, 'community')], default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_description',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='video',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='resume',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
    ]
