# Generated by Django 2.0.1 on 2020-02-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_country'),
        ('users', '0004_remove_teacher_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Country'),
        ),
    ]
