# Generated by Django 2.1.7 on 2020-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_availabletime_packagelessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
