# Generated by Django 2.1.7 on 2020-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200225_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='available_hours',
            field=models.TimeField(default=None, null=True),
        ),
    ]
