# Generated by Django 2.1.7 on 2020-02-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200225_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availableTime', to='users.Teacher'),
        ),
    ]
