# Generated by Django 3.0.4 on 2020-03-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200229_1610'),
        ('users', '0016_auto_20200305_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='system.SubCategory'),
        ),
    ]
